"""
This script preprocesses the dementia dataset we will
be using in our ML pipeline to train our simple classification model.
"""
import pandas as pd
from sklearn.preprocessing import MinMaxScaler # Generated by ChatGPT 5.1 at 3:29 PM On 11/21/25

def preprocess_cleaned_data(df):
    """
    Preprocessing Decision #4: Binary encode the "M/F" column

    Rationale:
    1) The "M/F" variable is a categorical variable, and it would be valuable
    to convert to a numerical variable in order for our model to take gender into
    consideration when predicting the "Group" variable for a given patient.
    2) Moreover, since there are only two possible values for "M/F" (M or F), a binary encoding should
    suffice.
    3) A one-hot encoding would unncessarily increase the dimensionality of feature
    space.
    """
    df["M/F"] = df["M/F"].map(lambda x: 1 if x == "M" else 0)

    """
    Preprocessing Decision #5: Binary encode the "Group" column

    Rationale:
    1) The "Group" variable is a categorical variable, and it is imperative
    to convert it to a numerical variable since our model needs to predict the "Group"
    of a given patient.
    2) A value of "Converted" in this context means that the given patient was diagnosed
    as not having dementia at the time of their initial visit and later diagnosed as
    having dementia at a later visit, meaning that a patient who is "Converted" effectively has dementia.
    3) Given the pairplot of numerical features where "Group" was differentiated in visualize_data.py, it did
    not appear that the "Converted" data points had any meaningful patterns for any of the numerical features.
    4) Therefore, a binary encoding should suffice (all patients that have dementia
    designated as 0 and all other patients as 1). Similarly to the previous preprocessing
    decision, a one-hot encoding in this context would unncessarily increase the
    dimensionality of feature space.
    """
    df["Group"] = df["Group"].map(lambda x: 0 if x == "Nondemented" else 1)

    """
    Preprocessing Decision #6: Apply Min-Max scaling to all numerical variables except
    for "Group" and "M/F"

    Rationale:
    1) According to the "Measures of Dispersion:" printed output from report_descriptive_statistics.py,
    the standard deviations of the numerical variables vary in magnitude to a significant extent
    (ex. "MR Delay" has a standard deviation of 635.4851184823334 whereas "EDUC" has a standard
    deviation of 2.8763394655221344) hence the need for some form of standardization in terms of
    magnitude.
    2) Min-Max scaling reduces the range to [0, 1] which would assist with standardization in
    terms of magnitude.
    3) Min-Max scaling does not have any distribution assumptions (valuable since, according to printed output
    from report_descriptive_statistics.py, some variables have noticeable right skew (i.e. CDR with a skewness
    of 1.3193180197402516) and some have noticeable left skew (i.e. MMSE with a skewness of -2.366086132004125)).
    4) Since the "M/F" and "Group" columns are binary in value, so applying Min-Max scaling
    to these columns would reduce interpretability.
    """
    scaler = MinMaxScaler()
    numerical_vars_to_transform = ["Visit", "MR Delay", "Age", "EDUC", "SES", "MMSE", "CDR", "eTIV", "nWBV", "ASF"]
    for var in numerical_vars_to_transform:
        df[var] = scaler.fit_transform(df[[var]])
    
    # Output this cleaned DataFrame as a csv file.
    df.to_csv("data/processed/preprocessed_dementia_dataset.csv", index=False)

    # Return the fully preprocessed Pandas DataFrame.
    return df