# Import dependencies.
from google.cloud import storage

# The following two lines of code were generated by ChatGPT 5.1 on 11/21/25 at 10:24 PM
from dotenv import load_dotenv
load_dotenv()

# Create a client.
client = storage.Client()

# Retrieve the bucket with the cleaned data.
bucket = client.get_bucket("mlops-dementia-classifier")

# Retrieve the cleaned data in the bucket.
data = bucket.get_blob("preprocessed_dementia_dataset.csv")

# Verify the data was retrieved by printing the list of blobs in the bucket.
print(data)