"""
This script cleans the dementia dataset we will
be using in our ML pipeline to train our simple classification model.
"""
import pandas as pd

# Download the dataset as a pandas DataFrame.
df = pd.read_csv("data/raw/dementia_dataset.csv")
print(df.head(10))

"""
Preprocessing Decision #1: Remove the "Hand" Column.

Rationale: All participants are all right-handed. Therefore, having a hand column would not
be valuable for predicting the "Group" category.
"""
df.drop(columns=["Hand"], inplace=True)
print(df.head(10))

"""
Preprocessing Decision #2: Drop all rows with NaN.

Rationale:
1) According to the printed output from the assess_data_structure.py file, it was found
that there were 19/373 missing values for SES (around 5% of its values were missing) and
that there were 2/373 missing values for MMSE (around 0.5% of its values were missing).
Therefore, dropping all rows with NaN would little to no effect on model's ability
to predict the "Group" catgeory for a given patient.
"""
df.dropna(inplace=True)
print(df.head(10))

# Confirm there are no more missing values in the DataFrame.
print("")
print("Number of Missing Values per Column:")
for col in df.columns:
    print(col + ": " + str(df[col].isna().sum()))

"""
Preprocessing Decision #3: Remove the "Subject ID" and "MRI ID" Columns

Rationale:
1) The last digit of all the "MRI ID" values are the same as the "Visit" values,
meaning that the "MRI ID" does not contribute any information that "Visit" does not.
Therefore, it is not worthwile to numerically encode the "MRI ID" column, and the
"MRI ID" column should be removed.
2) The "Subject ID" column is just an identifier rather than a feature with any
meaning. Therefore, it is not worthwile to numerically encode the "Subject ID" column,
and the "Subject ID" column should be removed.
"""
df.drop(columns=["Subject ID", "MRI ID"], inplace=True)
print(df.head(10))

# Output this cleaned DataFrame as a csv file.
df.to_csv("data/processed/cleaned_dementia_dataset.csv", index=False) # index=false part generated by ChatGPT 5.1 at 2:00 PM on 11/22/25