"""
This script reports descriptive statistics for the dementia dataset we will
be using in our ML pipeline to train our simple classification model.
"""
import pandas as pd

# Download the dataset as a pandas DataFrame.
df = pd.read_csv("../../data/raw/dementia_dataset.csv")

# Create an array with the column labels corresponding to numerical columns (found from printed output in assess_data_structure.py)
numerical_vars = ["Visit", "MR Delay", "Age", "EDUC", "SES", "MMSE", "CDR", "eTIV", "nWBV", "ASF"]

# Report the central tendency measures (mean, median, mode) for numerical variables.
print("Central Tendency Measures:")
print("")
for var in numerical_vars:
    print(var + ": ")
    print("Mean:", df[var].mean())
    print("Median:", df[var].median())
    print("Mode:", df[var].mode().iloc[0]) # .iloc[0] part generated by ChatGPT 5.1 at 1:49 PM on 11/19/25
    print("")

# Report the measures of dispersion (range, variance, standard deviation) for numerical variables.
print("Measures of Dispersion:")
print("")
for var in numerical_vars:
    print(var + ": ")
    print("Range:", df[var].max() - df[var].min())
    print("Variance:", df[var].var())
    print("Standard Deviation:", df[var].std())
    print("")

# Report the distribution of the numerical variables (normal, skewed, etc.).
print("Distributions of Numerical Variables:")
print("")
for var in numerical_vars:
    print(var + ": ")
    print("Skewness:", df[var].skew())
    print("Kurtosis:", df[var].kurt())
    print("")